### ISSUE TITLE
 face recognition

### ISSUE THREAD

**Issue by Mohammed-Bin-Mohammed** [cagbal/cob_people_object_detection_tensorflow#52] opened 2020-10-07 07:28 UTC
i need to apply your application to turtlebot3  could you help me

**Comment by cagbal** [comment] 2020-10-07 11:24
Hi, I am closing this issue because this is not a bug or feature request. Unfortunately, I could not help at the moment, since this is a ROS package and basic knowledge of ROS suffices to run.

**Closed as completed by cagbal** 2020-10-07 11:24 UTC

**Comment by Mohammed-Bin-Mohammed** [comment] 2020-10-07 13:53
ImportError: No module named tensorflow
[cob_people_object_detection_detection-2] process has died [pid 7402, exit
code 1, cmd
/home/autobot/catkin_ws/src/ros_people_object_detection_tensorflow/src/cob_people_object_detection_tensorflow.py
__name:=cob_people_object_detection_detection
__log:=/home/autobot/.ros/log/2c2fe6ba-08a4-11eb-9812-e4a471aa99a2/cob_people_object_detection_detection-2.log].
log file:
/home/autobot/.ros/log/2c2fe6ba-08a4-11eb-9812-e4a471aa99a2/cob_people_object_detection_detection-2*.log
[cob_face_recognizer-3] process has died [pid 7403, exit code 1, cmd
/home/autobot/catkin_ws/src/ros_people_object_detection_tensorflow/src/face_recognizer.py
__name:=cob_face_recognizer
__log:=/home/autobot/.ros/log/2c2fe6ba-08a4-11eb-9812-e4a471aa99a2/cob_face_recognizer-3.log].
log file:
/home/autobot/.ros/log/2c2fe6ba-08a4-11eb-9812-e4a471aa99a2/cob_face_recognizer-3*.log


sorry for that but it couldn't be run with me this error appear to me could
you please help


‫في الأربعاء، 7 أكتوبر 2020 في 2:24 م تمت كتابة ما يلي بواسطة ‪cagatay
odabasi‬‏ <‪notifications@github.com‬‏>:‬

**Comment by Mohammed-Bin-Mohammed** [comment] 2020-10-07 13:53
it is my graduation project last step

‫في الأربعاء، 7 أكتوبر 2020 في 4:53 م تمت كتابة ما يلي بواسطة ‪Mohammed
Sumaini‬‏ <‪m.sumaini@gmail.com‬‏>:‬
